### PR TITLE
make git optional in sandbox tutorials

### PR DESCRIPTION
**Pull request by Rookeret73**

### CODE REVIEW

**Comment by MickaelAlliel** [comment]
@Rookeret73 is there any benefit in explaining the differences between explorook and simplehttps?
When you say choose Local Filesystem and they see 2 options they've never seen before its confusing

**Comment by Rookeret73** [comment]
Happy flow is if they use github.
This change was just meant to highlight that local filesystem is optional.
One of the users who did user testing got stuck on it.

I think a full solution would be to remove https and add a full guide for explorook.
But I don't want the onboarding experience to wait for such a change.

**Comment by LiranLast** [comment]
@iglizer is on the verge of making simple-https hidden by default. You might want to coordinate with him :)

**Comment by Rookeret73** [comment]
Will do :)
For now, can you please approve?

**Comment by LiranLast** [comment]
Better have @MickaelAlliel rescind his review

**Pull request merged**
