### PR TITLE
RK-9146 - Update use-cases.md

### PR DESCRIPTION
**Pull request by ElinorSwery**

### CODE REVIEW

**Review by ElDuderinos — APPROVED** [review]

**Comment by ElDuderinos** [comment]
@ElinorSwery you have conflicts

**Comment by ElDuderinos** [comment]
@ElinorSwery after the last commit this PR has 0 changes...
Is this a duplicate of https://github.com/Rookout/docs/pull/416
?

**Comment by ElinorSwery** [comment]
Duplicate of https://github.com/Rookout/docs/pull/416

**Pull request closed without merging**
