### PR TITLE
RK-15135 - Remove 'debugging node modules' section

### PR DESCRIPTION
**Pull request by naomirookout**
We don't recommend this to anyone anymore (@ElDuderinos )

### CODE REVIEW

**Comment by LiranLast** [comment]
Why remove this section?

It's a bit out date, but fairly important :)

**Comment by ElDuderinos** [comment]
> Why remove this section?
> 
> It's a bit out date, but fairly important :)

When was the last time anyone used this?
No one knows about the .rookout file except you and me.

**Comment by LiranLast** [comment]
The contents are very much out of date.

But I answered a support ticket about third-party debugging about 3 minutes ago :)

**Comment by naomirookout** [comment]
@LiranLast this docs change is for this QoL ticket - https://rookout.atlassian.net/browse/RK-15135

**Comment by LiranLast** [comment]
Hiding something is not deprecating it :)

**Pull request closed without merging**
