### PR TITLE
RK-10174 - Updated built in labels

### PR DESCRIPTION
**Pull request by jhendrick**

### CODE REVIEW

**Comment by lirook** [comment]
The whole section of "Built-In Labels" is misleading. It talks about filters, and not labels. Labels are one type of filter.
I'd find another place to put it or remove it altogether.

**Comment by jhendrick** [comment]
> Hey @jhendrick, this update is awesome! but, the whole section of "Built-In Labels" is misleading. It talks about filters, and not labels which are one type of filter. I'd find another place to put it or remove it altogether.

@lirook Makes sense, I do think it's valuable to point this information out. Should we just call the section built in Filters?

**Comment by lirook** [comment]
In my opinion, it's obvious. But it's your decision :)

**Comment by jhendrick** [comment]
@lirook Removed the section. Please approve when you have a moment.

**Review by lirook — APPROVED** [review]

**Pull request merged**
