### PR TITLE
text_file and json_file are agent only

### PR DESCRIPTION
**Pull request by Rookeret73**
and python only?
#2397

### CODE REVIEW

**Comment by LiranLast** [comment]
@Rookeret73 I think it makes more sense to divide operations into categories:

- SaaS
- Network
- FileSystem

Anyway, as I have said in other places, all references to Python should probably be removed from these docs.

**Comment by Rookeret73** [comment]
> @Rookeret73 I think it makes more sense to divide operations into categories:
> 
> * SaaS
> * Network
> * FileSystem
> 
> Anyway, as I have said in other places, all references to Python should probably be removed from these docs.

@LiranLast Done and Done.

**Comment by MickaelAlliel** [comment]
@Rookeret73 Ben is on vacation he won't be able to approve :)
@LiranLast

**Comment by Rookeret73** [comment]
> @Rookeret73 Ben is on vacation he won't be able to approve :)
> @LiranLast

Kitbeg granted :)

**Pull request merged**
