### PR TITLE
Update circle ci node version  - 16.17.0

### PR DESCRIPTION
**Pull request by hopemanryan**
https://rookout.atlassian.net/browse/RK-13765

### CODE REVIEW

**Comment by Urook** [comment]
@hopemanryan Is node 17 still in active support? 
https://nodejs.org/en/about/releases/

**Comment by Urook** [comment]
> @hopemanryan Is node 17 still in active support? https://nodejs.org/en/about/releases/

@hopemanryan According to this it reached EOL:
https://endoflife.date/nodejs

**Comment by Urook** [comment]
@hopemanryan Update thr title

**Comment by hopemanryan** [comment]
> @hopemanryan Update the title

done

**Review by Urook — APPROVED** [review]

**Pull request merged**
