### PR TITLE
RK-9997 - Updated Debug session docs

### PR DESCRIPTION
**Pull request by jhendrick**

### CODE REVIEW

**Review by lirook — COMMENTED** [review]
@jhendrick this all looks great.
Just one thing - the arrow to server selection image is pretty low res, would you mind taking it again? :)

**Review by ElinorSwery — CHANGES_REQUESTED** [review]
Spelling mistake? “drowndown” should be dropdown?
For the various filtering components - do we want to also mention the K8 label?

**Review by jhendrick — COMMENTED** [review]
Fixed

**Review by lirook — APPROVED** [review]
:)

**Pull request merged**
