### PR TITLE
RK-10051 - Fixed Windows path

### PR DESCRIPTION
**Pull request by jhendrick**

### CODE REVIEW

**Comment by ElDuderinos** [comment]
@jhendrick I'm not sure this is always true, probably in some occasions it will be under "roaming" and sometimes not.
@dan505512 can probably help out here.
Anyway, we need to update this entire page, as we no longer clone locally all the repositories in on prem git providers.

**Comment by dan505512** [comment]
1. We use %appdata% there so it's not supposed to be under roaming
2. We removed this integration for now so there's no actual need to update this unless the update is removing this part of the docs

**Review by dan505512 — CHANGES_REQUESTED** [review]
We should just remove this part altogether

**Comment by jhendrick** [comment]
>     1. We use %appdata% there so it's not supposed to be under roaming
> 
>     2. We removed this integration for now so there's no actual need to update this unless the update is removing this part of the docs

I've seen it appear in a few different places. For the installation call yesterday it was under Roaming, so I had figured it's always there. But ok, no problem

**Comment by jhendrick** [comment]
> @jhendrick I'm not sure this is always true, probably in some occasions it will be under "roaming" and sometimes not.
> @dan505512 can probably help out here.
> Anyway, we need to update this entire page, as we no longer clone locally all the repositories in on prem git providers.

@ElDuderinos Why would it change?

**Comment by ElDuderinos** [comment]
We used to clone it locally when we used the cli integration, we no longer do that, but have implemented direct API integration.

**Pull request closed without merging**
