### PR TITLE
RK-10855 - Delete breakpoints-reference.md

### PR DESCRIPTION
**Pull request by lirook**
I think there's no reason to confuse customers with all this info, we don't want them to edit the JSON except for some very extreme cases. Moreover, most of the info here is incorrect.
Let's remove this page and keep it as internal documentation.

### CODE REVIEW

**Comment by Rookeret73** [comment]
I agree, most things here shouldn't be customer facing, and customers shouldn't handle JSON if we can avoid it.
Some stuff may be useful to advanced users (data redaction, include packages, high level explanation about collection level). But these can be re-added to another docs section later on.

Let's make sure our team knows where to find the internal docs as part of troubleshooting steps.
And let's make sure references to this page from other docs pages are removed if necessary.

**Review by Rookeret73 — APPROVED** [review]

**Comment by lirook** [comment]
@eladuzan94 @ElinorSwery @jhendrick 
Looping you guys in. Do you have this info documented somewhere else? Is it okay with you that I delete it?

**Comment by jhendrick** [comment]
> 

I don't think we have it documented elsewhere but I agree it's probably best to remove from customer view since as of now its more confusing than anything.

**Pull request merged**
