### PR TITLE
RK-13821 - Throw error on broken markdown links

### PR DESCRIPTION
**Pull request by naomirookout**
https://docusaurus.io/docs/api/docusaurus-config#onBrokenMarkdownLinks

### CODE REVIEW

**Comment by ElDuderinos** [comment]
@hopemanryan are we doing this or not?

**Comment by hopemanryan** [comment]
Never saw this pr 

Lgtm

**Review by hopemanryan — APPROVED** [review]

**Comment by Urook** [comment]
@naomirookout You have conflicts

**Review by Urook — APPROVED** [review]

**Pull request merged**
